version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:4
    command: >
      bash -c "gem install webrick &&
              jekyll serve --watch --host 0.0.0.0"
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle  # Cache gems
    working_dir: /srv/jekyll
    environment:
      - JEKYLL_ENV=development 